export const restaurant_info = [
  {
    _id: "65aa34bddd4d52bbe59cc52e",
    name: "Naans's Avacado",
    cuisines: ["Biryani", "Pannes Butter Masala"],
    starRating: "4.9",
    imageUrl:
      "https://images.unsplash.com/photo-1590846406792-0adc7f938f1d?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8cmVzdGF1cmFudHxlbnwwfHwwfHx8MA%3D%3D",
    __v: 0,
    id: "356932",
    areaName: "SV Colleges",
    cloudinaryImageId: "oipydn0wgr0mhtc4vfwc",
    locality: "Karakambadi Road",
  },
  {
    _id: "65eec68508b6211c1701aa4a",
    id: "356932",
    name: "Pizza Hut",
    cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
    locality: "STV Nagar",
    areaName: "Tirumala",
    costForTwo: "₹350 for two",
    cuisines: ["Pizzas"],
    avgRating: "4.3",
    parentId: "721",
    avgRatingString: "4.3",
    totalRatingsString: "5K+",
  },
  {
    _id: "65eec89932247e61dbee52fc",
    id: "80107",
    name: "Di Table 9",
    cloudinaryImageId: "y7bpsdht2ngjp9ihon0d",
    locality: "Korramenugunta",
    areaName: "Near Bustand",
    costForTwo: "₹380 for two",
    cuisines: ["Biryani", "Chinese", "South Indian"],
    avgRating: "4.2",
    parentId: "353708",
    avgRatingString: "4.2",
    totalRatingsString: "10K+",
  },
  {
    _id: "65eec8bc32247e61dbee52fd",
    id: "87108",
    name: "Chillies Restaurant - Air Bypass Road",
    cloudinaryImageId: "nurlkpydl5pcnql1apwj",
    locality: "Air Bypass Road",
    areaName: "Air Bypass Road",
    costForTwo: "₹200 for two",
    cuisines: ["Biryani", "Chinese", "Hyderabadi", "Tandoor"],
    avgRating: "4.3",
    parentId: "22252",
    avgRatingString: "4.3",
    totalRatingsString: "10K+",
  },
  {
    _id: "65eec9d232247e61dbee52fe",
    id: "108117",
    name: "Lasa Food Court",
    cloudinaryImageId: "4ef4b80b691438b93313eea82e12d55c",
    locality: "Tiruchinoor Road",
    areaName: "Padmavathi Nagar",
    costForTwo: "₹250 for two",
    cuisines: ["Biryani", "Chinese", "Hyderabadi", "Tandoor"],
    avgRating: "4.1",
    parentId: "6911",
    avgRatingString: "4.1",
    totalRatingsString: "10K+",
  },
  {
    _id: "65eec9f232247e61dbee52ff",
    id: "80056",
    name: "Spicy Paradise",
    cloudinaryImageId: "cbacc79b1840acc362aff7b9238c83d7",
    locality: "Tata Nagar",
    areaName: "Bus Stand Road",
    costForTwo: "₹300 for two",
    cuisines: ["Biryani", "Chinese", "Hyderabadi", "Tandoor", "Ice Cream"],
    avgRating: "4",
    parentId: "13072",
    avgRatingString: "4.0",
    totalRatingsString: "10K+",
  },
  {
    _id: "65eeca0132247e61dbee5300",
    id: "80072",
    name: "Deforest Restaurant",
    cloudinaryImageId: "mhy34atov6etknpijkiu",
    locality: "Mr Pally",
    areaName: "Tata Nagar",
    costForTwo: "₹250 for two",
    cuisines: [
      "Biryani",
      "Chinese",
      "Hyderabadi",
      "Tandoor",
      "North Indian",
      "South Indian",
    ],
    avgRating: "4",
    parentId: "14044",
    avgRatingString: "4.0",
    totalRatingsString: "10K+",
  },
  {
    _id: "65eeca1132247e61dbee5301",
    id: "607702",
    name: "Pulse Grameena Biryani",
    cloudinaryImageId: "w7fktuea0z4p0duehcg4",
    locality: "Raghavendra Nagar",
    areaName: "Korramenugunta",
    costForTwo: "₹300 for two",
    cuisines: ["Biryani", "Seafood"],
    avgRating: "4.1",
    parentId: "361582",
    avgRatingString: "4.1",
    totalRatingsString: "1K+",
  },
  {
    _id: "65eeca4b32247e61dbee5302",
    id: "80127",
    name: "Kwalitys Spicy Family Restaurant",
    cloudinaryImageId: "xdfha5siz8az8frn4u8g",
    locality: "Tirupati Road",
    areaName: "Tirumala Bypass Road",
    costForTwo: "₹300 for two",
    cuisines: ["Biryani", "Chinese", "Hyderabadi", "Tandoor"],
    avgRating: "4.2",
    parentId: "452956",
    avgRatingString: "4.2",
    totalRatingsString: "10K+",
  },
  {
    _id: "65eeca8b32247e61dbee5303",
    id: "417917",
    name: "Di Table 9 New",
    cloudinaryImageId: "qo7c3w7pyuqp2vhtenny",
    locality: "Kapila Teertham Road",
    areaName: "KT Road",
    costForTwo: "₹250 for two",
    cuisines: ["Biryani", "South Indian"],
    avgRating: "4.2",
    parentId: "353706",
    avgRatingString: "4.2",
    totalRatingsString: "10K+",
  },
  {
    _id: "65eeca9c32247e61dbee5304",
    id: "98464",
    name: "Perambur Sri Srinivasa PS4 Pure Veg Restaurant",
    cloudinaryImageId: "bnhseopcrbvdcarasz2c",
    locality: "Tirumala Bypass Road",
    areaName: "Tirumala Bypass Road",
    costForTwo: "₹200 for two",
    cuisines: [
      "South Indian",
      "Sweets",
      "North Indian",
      "Chinese",
      "Chaat",
      "Juices",
    ],
    avgRating: "4.5",
    veg: true,
    parentId: "14153",
    avgRatingString: "4.5",
    totalRatingsString: "10K+",
  },
  {
    _id: "65eecab732247e61dbee5305",
    id: "80775",
    name: "Pulse",
    cloudinaryImageId: "mnyzdoe14wskbrknamyu",
    locality: "Bairagi patteda",
    areaName: "AIR By Pass Road",
    costForTwo: "₹350 for two",
    cuisines: [
      "Biryani",
      "Chinese",
      "Kebabs",
      "Tandoor",
      "South Indian",
      "Indian",
      "Seafood",
      "Mughlai",
      "Hyderabadi",
      "Grill",
    ],
    avgRating: "4.2",
    parentId: "6886",
    avgRatingString: "4.2",
    totalRatingsString: "10K+",
  },
  {
    _id: "65eecad632247e61dbee5306",
    id: "80143",
    name: "Manal Restaurant",
    cloudinaryImageId: "zl3arydtzgaelljtgesm",
    locality: "Khadi Colony",
    areaName: "Kt Road",
    costForTwo: "₹250 for two",
    cuisines: ["Biryani", "Chinese", "Hyderabadi", "Tandoor"],
    avgRating: "4.2",
    parentId: "14176",
    avgRatingString: "4.2",
  },
  {
    _id: "65eecae432247e61dbee5307",
    id: "87109",
    name: "Chillies Restaurant - KT Road",
    cloudinaryImageId: "dfexphbwumz4zbambcyy",
    locality: "Kapila Teertham Road",
    areaName: "KT Road",
    costForTwo: "₹200 for two",
    cuisines: ["Biryani", "Chinese", "Hyderabadi", "Tandoor"],
    avgRating: "4.3",
    parentId: "14037",
    avgRatingString: "4.3",
    totalRatingsString: "10K+",
  },
];

// // export const restaurant_info = [
// //   {
// //     id: "65aa382e76beec9a045d26d6",
// //     name: "Robo Diner",
// //     cloudinaryImageId: "wgwl0lbhnsoz6rnjgotq",
// //     locality: "Air by pass Road",
// //     areaName: "Airbypass Road",
// //     costForTwo: "₹300 for two",
// //     cuisines: [
// //       "Biryani",
// //       "North Indian",
// //       "Chinese",
// //       "Indian",
// //       "Tandoor",
// //       "Desserts",
// //       "South Indian",
// //     ],
// //     avgRating: 3.7,
// //     menu: {
// //       items: [
// //         {
// //           name: "Biryani",
// //           id: 1,
// //         },
// //         {
// //           name: "Chicken Lollypop",
// //           id: 2,
// //         },
// //       ],
// //     },
// //   },

// //   {
// //     id: "356932",
// //     name: "Pizza Hut",
// //     cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
// //     locality: "STV Nagar",
// //     areaName: "Tirumala",
// //     costForTwo: "₹350 for two",
// //     cuisines: ["Pizzas"],
// //     avgRating: 4.3,
// //     parentId: "721",
// //     avgRatingString: "4.3",
// //     totalRatingsString: "5K+",
// //   },

// //   {
// //     id: "65aa388b76beec9a045d26d8",
// //     name: "Table 9",
// //     cloudinaryImageId: "65aa388b76beec9a045d26d8",
// //     locality: "Air by pass Road",
// //     areaName: "Airbypass Road",
// //     costForTwo: "₹300 for two",
// //     cuisines: ["Biryani", "North Indian", "Chinese", "South Indian"],
// //     avgRating: 4.7,
// //     menu: {
// //       items: [
// //         {
// //           name: "Biryani",
// //           id: 1,
// //         },
// //         {
// //           name: "Chicken Lollypop",
// //           id: 2,
// //         },
// //       ],
// //     },
// //   },

// //   {
// //     id: "65acb1c772b09ff4f952912e",
// //     name: "Pulse Grameena Biryani",
// //     cloudinaryImageId: "w7fktuea0z4p0duehcg4",
// //     locality: "Raghavendra Nagar",
// //     areaName: "Korramenugunta",
// //     costForTwo: "₹300 for two",
// //     cuisines: ["Biryani ", "Seafood "],
// //     avgRating: 3.7,
// //     parentId: "361582",
// //     avgRatingString: "3.7",
// //     totalRatingsString: "1K+",
// //   },

// //   {
// //     id: "65aa3a7976beec9a045d26de",
// //     name: "Kwalitys Spicy Family Restaurant",
// //     cloudinaryImageId: "xdfha5siz8az8frn4u8g",
// //     locality: "Tirupati Road",
// //     areaName: "Tirumala Bypass Road",
// //     costForTwo: "₹300 for two",
// //     cuisines: ["Biryani ", "Chinese ", "Hyderabadi ", "Tandoor "],
// //     avgRating: 4,
// //     parentId: "452956",
// //     avgRatingString: "4.0",
// //     totalRatingsString: "10K+",
// //   },

// //   {
// //     id: "65aa3ac076beec9a045d26e0",
// //     name: "Spicy Paradise",
// //     cloudinaryImageId: "cbacc79b1840acc362aff7b9238c83d7",
// //     locality: "Tata Nagar",
// //     areaName: "Bus Stand Road",
// //     costForTwo: "₹300 for two",
// //     cuisines: ["Biryani ", "Chinese ", "Hyderabadi ", "Tandoor ", "Ice Cream "],
// //     avgRating: 3.7,
// //     parentId: "13072",
// //     avgRatingString: "3.7",
// //     totalRatingsString: "10K+",
// //   },

// //   {
// //     id: "",
// //     name: "Manal Restaurant",
// //     cloudinaryImageId: "zl3arydtzgaelljtgesm",
// //     locality: "Khadi Colony",
// //     areaName: "Kt Road",
// //     costForTwo: "₹250 for two",
// //     cuisines: ["Biryani ", "Chinese ", "Hyderabadi ", "Tandoor "],
// //     avgRating: 3.9,
// //     parentId: "14176",
// //     avgRatingString: "3.9",
// //     totalRatingsString: "10K+",
// //   },

// //   {
// //     id: "65aa3b0f76beec9a045d26e4",
// //     name: "Chillies Restaurant - Air Bypass Road",
// //     cloudinaryImageId: "nurlkpydl5pcnql1apwj",
// //     locality: "Air Bypass Road",
// //     areaName: "Air Bypass Road",
// //     costForTwo: "₹200 for two",
// //     cuisines: ["Biryani ", "Chinese ", "Hyderabadi ", "Tandoor "],
// //     avgRating: 4.1,
// //     parentId: "22252",
// //     avgRatingString: "4.1",
// //     totalRatingsString: "10K+",
// //   },

// //   {
// //     id: "",
// //     name: "Chillies Restaurant - Air Bypass Road",
// //     cloudinaryImageId: "nurlkpydl5pcnql1apwj",
// //     locality: "Air Bypass Road",
// //     areaName: "Air Bypass Road",
// //     costForTwo: "₹200 for two",
// //     cuisines: ["Biryani ", "Chinese ", "Hyderabadi ", "Tandoor "],
// //     avgRating: 4.1,
// //     parentId: "22252",
// //     avgRatingString: "4.1",
// //     totalRatingsString: "10K+",
// //   },
// //   {
// //     id: "65aa34bddd4d52bbe59cc52e",
// //     name: "Naans's Avacado",
// //     cuisines: ["Biryani", "Pannes Butter Masala"],
// //     starRating: "4.9",
// //     cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
// //     imageUrl:
// //       "https://images.unsplash.com/photo-1590846406792-0adc7f938f1d?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8cmVzdGF1cmFudHxlbnwwfHwwfHx8MA%3D%3D",
// //     __v: 0,
// //   },
// //   {
// //     _id: "65aa382e76beec9a045d26d6",
// //     name: "Pulse",
// //     cuisines: [
// //       "Biryani ",
// //       "Chinese ",
// //       "Kebabs ",
// //       "Tandoor ",
// //       "South Indian ",
// //       "Indian ",
// //     ],
// //     starRating: "3.8",
// //     imageUrl:
// //       "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_288,h_360/mnyzdoe14wskbrknamyu",
// //     __v: 0,
// //   },
// // ];

// export const restaurant_info = [
//   [
//     {
//       _id: "65aa34bddd4d52bbe59cc52e",
//       name: "Naans's Avacado",
//       cuisines: ["Biryani", "Pannes Butter Masala"],
//       starRating: "4.9",
//       imageUrl:
//         "https://images.unsplash.com/photo-1590846406792-0adc7f938f1d?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8cmVzdGF1cmFudHxlbnwwfHwwfHx8MA%3D%3D",
//       __v: 0,
//     },
//     {
//       _id: "65aa382e76beec9a045d26d6",
//       name: "Pulse",
//       cuisines: [
//         "Biryani ",
//         "Chinese ",
//         "Kebabs ",
//         "Tandoor ",
//         "South Indian ",
//         "Indian ",
//       ],
//       starRating: "3.8",
//       imageUrl:
//         "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_288,h_360/mnyzdoe14wskbrknamyu",
//       __v: 0,
//     },
//     {
//       _id: "65aa388b76beec9a045d26d8",
//       name: "Di Table 9 New",
//       cuisines: [
//         "South Indian ",
//         "North Indian ",
//         "Biryani ",
//         "Tandoor ",
//         "Chinese ",
//       ],
//       starRating: "3.9",
//       imageUrl:
//         "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_288,h_360/qo7c3w7pyuqp2vhtenny",
//       __v: 0,
//     },
//     {
//       _id: "65aa38f376beec9a045d26da",
//       name: "Perambur Sri Srinivasa PS4 Pure Veg Restaurant",
//       cuisines: [
//         "South Indian ",
//         "Sweets ",
//         "North Indian ",
//         "Chinese ",
//         "Chaat ",
//         "Juices ",
//       ],
//       starRating: "4.3",
//       imageUrl:
//         "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_288,h_360/bnhseopcrbvdcarasz2c",
//       __v: 0,
//     },
//     {
//       _id: "65aa3a4f76beec9a045d26dc",
//       name: "Pulse Grameena Biryani",
//       cuisines: ["Biryani ", "Seafood "],
//       starRating: "3.7",
//       imageUrl:
//         "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_288,h_360/w7fktuea0z4p0duehcg4",
//       __v: 0,
//     },
//     {
//       _id: "65aa3a7976beec9a045d26de",
//       name: "Kwalitys Spicy Family Restaurant",
//       cuisines: ["Biryani ", "Chinese ", "Hyderabadi ", "Tandoor "],
//       starRating: "4",
//       imageUrl:
//         "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_288,h_360/xdfha5siz8az8frn4u8g",
//       __v: 0,
//     },
//     {
//       _id: "65aa3ac076beec9a045d26e0",
//       name: "Spicy Paradise",
//       cuisines: [
//         "Biryani ",
//         "Chinese ",
//         "Hyderabadi ",
//         "Tandoor ",
//         "Ice Cream ",
//       ],
//       starRating: "3.7",
//       imageUrl:
//         "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_288,h_360/cbacc79b1840acc362aff7b9238c83d7",
//       __v: 0,
//     },
//     {
//       _id: "65aa3aea76beec9a045d26e2",
//       name: "Manal Restaurant",
//       cuisines: ["Biryani ", "Chinese ", "Hyderabadi ", "Tandoor "],
//       starRating: "3.9",
//       imageUrl:
//         "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_288,h_360/zl3arydtzgaelljtgesm",
//       __v: 0,
//     },
//     {
//       _id: "65aa3b0f76beec9a045d26e4",
//       name: "Chillies Restaurant - Air Bypass Road",
//       cuisines: ["Biryani ", "Chinese ", "Hyderabadi ", "Tandoor "],
//       starRating: "4.1",
//       imageUrl:
//         "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_288,h_360/nurlkpydl5pcnql1apwj",
//       __v: 0,
//     },
//     {
//       _id: "65aa4fa5e2038be32f9c997a",
//       name: "Bawarchi By Nawaabs",
//       cuisines: ["Biryani ", "Chinese ", "Hyderabadi ", "Tandoor "],
//       starRating: "3.7",
//       imageUrl:
//         "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_288,h_360/b654ab5016e0fb29bf21436922029ce1",
//       __v: 0,
//     },
//     {
//       _id: "65aa6c48d7055899e8da6d76",
//       name: "Mongoose Dine",
//       cuisines: ["Biryani ", "Chinese ", "Hyderabadi ", "Tandoor "],
//       starRating: "3.5",
//       imageUrl:
//         "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_288,h_360/b654ab5016e0fb29bf21436922029ce1",
//       __v: 0,
//     },
//     {
//       _id: "65acaef372b09ff4f9529128",
//       name: "KFC",
//       cuisines: ["Chicken", "Burger"],
//       starRating: "4.2",
//       imageUrl:
//         "https://media-cdn.tripadvisor.com/media/photo-s/15/8c/9d/25/full-meal.jpg",
//       __v: 0,
//     },
//     {
//       _id: "65acb03172b09ff4f952912a",
//       name: "Di Table 9 New",
//       cuisines: [
//         "South Indian ",
//         "North Indian ",
//         "Biryani ",
//         "Tandoor ",
//         "Chinese ",
//       ],
//       starRating: "4.1",
//       imageUrl:
//         "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_288,h_360/qo7c3w7pyuqp2vhtenny",
//       __v: 0,
//     },
//     {
//       _id: "65acb11672b09ff4f952912c",
//       name: "Perambur Sri Srinivasa PS4 Pure Veg Restaurant",
//       cuisines: [
//         "South Indian ",
//         "Sweets ",
//         "North Indian ",
//         "Chinese ",
//         "Chaat ",
//         "Juices ",
//       ],
//       starRating: "4.2",
//       imageUrl:
//         "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_288,h_360/bnhseopcrbvdcarasz2c",
//       __v: 0,
//     },
//     {
//       _id: "65acb1c772b09ff4f952912e",
//       name: "Pulse",
//       cuisines: [
//         "Biryani ",
//         "Chinese ",
//         "Kebabs ",
//         "Tandoor ",
//         "South Indian ",
//         "Indian ",
//         "Seafood ",
//         "Mughlai ",
//         "Hyderabadi ",
//         "Grill ",
//       ],
//       starRating: "4.0",
//       imageUrl:
//         "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_288,h_360/mnyzdoe14wskbrknamyu",
//       __v: 0,
//     },
//     {
//       _id: "65acb25872b09ff4f9529130",
//       name: "Kwalitys Spicy Family Restaurant",
//       cuisines: ["Biryani ", "Chinese ", "Hyderabadi ", "Tandoor "],
//       starRating: "4.0",
//       imageUrl:
//         "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_288,h_360/xdfha5siz8az8frn4u8g",
//       __v: 0,
//     },
//     {
//       _id: "65acb2b572b09ff4f9529132",
//       name: "Manal Restaurant",
//       cuisines: ["Biryani ", "Chinese ", "Hyderabadi ", "Tandoor "],
//       starRating: "3.8",
//       imageUrl:
//         "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_288,h_360/zl3arydtzgaelljtgesm",
//       __v: 0,
//     },
//     {
//       _id: "65acb31072b09ff4f9529134",
//       name: "Chillies Restaurant - Air Bypass Road",
//       cuisines: ["Biryani ", "Chinese ", "Hyderabadi ", "Tandoor "],
//       starRating: "4.1",
//       imageUrl:
//         "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_288,h_360/nurlkpydl5pcnql1apwj",
//       __v: 0,
//     },
//     {
//       _id: "65acb35472b09ff4f9529136",
//       name: "Bawarchi By Nawaabs",
//       cuisines: ["Biryani ", "Chinese ", "Hyderabadi ", "Tandoor "],
//       starRating: "4.1",
//       imageUrl:
//         "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_288,h_360/b654ab5016e0fb29bf21436922029ce1",
//       __v: 0,
//     },
//   ],
// ];
